openapi: 3.0.3
info:
  description: >-
    A platform to calculate user's sustainability metrics
  title: Priceless Planet Data Services API
  version: 1.0.1
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support    
servers:
  - url: https://sandbox.api.mastercard.com/priceless-planet-coalition
    description: Mastercard Sandbox Environment
  - url: https://api.mastercard.com/priceless-planet-coalition
    description: Mastercard Production Environment
tags:
  - name: Impact Metrics
    description: >-
      An algorithm to detect how much the user contributes to the sustainability based on donation being made.
  - name: Planting Projects
    description: >-
      A tree planting project run by a charitable organisation.
paths:
  /impact-metrics:
    get:
      tags:
        - Impact Metrics
      summary: "Impact Metrics Calculation"
      description: "Response contains user's contribution to sustainability"
      operationId: getImpactMetrics
      parameters:
        - $ref: '#/components/parameters/DonationAmount'
        - $ref: '#/components/parameters/Currency'
      responses:
        '200':
          $ref: '#/components/responses/ImpactMetrics'
        '400':
          $ref: '#/components/responses/ImpactMetricsBadRequestError'
        '404':
          $ref: '#/components/responses/ImpactMetricsCurrencyNotFoundError'
  /planting-projects:
    get:
      tags:
        - Planting Projects
      summary: Retrieve planting projects
      description: >-
        Use this API to retrieve a list of planting projects.<br/>
      operationId: getPlantingProjects
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          $ref: '#/components/responses/PlantingProjects'
        '400':
          $ref: '#/components/responses/PlantingProjectsBadRequestError'
  /planting-projects/{id}:
    get:
      tags:
        - Planting Projects
      summary: Retrieve a planting project
      description: >-
        Use this API to retrieve a planting project by ID.<br/>
        Required roles: _priceless-planet-basic_, _priceless-planet-admin_
      operationId: getPlantingProject
      parameters:
        - $ref: '#/components/parameters/ResourceIdentifier'
      responses:
        '200':
          $ref: '#/components/responses/PlantingProject'
        '400':
          $ref: '#/components/responses/PlantingProjectBadRequestError'
        '404':
          $ref: '#/components/responses/PlantingProjectNotFoundError'
components:
  parameters:
    Limit:
      in: query
      name: limit
      schema:
        type: integer
        default: 10
        minimum: 1
      required: false
      description: The number of items you want the list to be limited to
      example: 10
    Offset:
      in: query
      name: offset
      schema:
        type: integer
        default: 0
        minimum: 0
      required: false
      description: The number of items to offset the start of the list from
      example: 0
    Sort:
      in: query
      name: sort
      schema:
        type: string
        pattern: '^[+\-,a-zA-Z]+$'
        minLength: 3
        maxLength: 50
        default: "-createdAt"
      required: false
      description: >-
        Allow ascending and descending sorting over one or more fields. For example:

        <ul>
          <li><b>sort=-name</b>: sort on the "name" field in descending order.
          <li><b>sort=+name</b>: sort on the "name" field in ascending order.
          <li><b>sort=name</b>: sort on the "name" field in ascending order (ascending is default).
          <li><b>sort=type,-date</b>: sort on the "type" field in ascending order, followed by the "date" field in descending order.
        </ul>
      example: "-id"
    ResourceIdentifier:
      in: path
      name: id
      schema:
        type: integer
        format: int64
        example: 1
      required: true
      description: A number which uniquely identifies a Priceless Planet resource
    DonationAmount:
      in: query
      name: donation_amount
      schema:
        type: number
        format: float
        example: 5.00
      required: true
      description: Amount being donated
    Currency:
      in: query
      name: currency
      schema:
        type: string
        format: ^[a-zA-Z]{3}$
        example: USD
      required: true
      description: 'Currency in which amount is being donated format ISO-4217'
  schemas:
    ImpactMetric:
      type: object
      properties:
        trees:
          description: Number of trees that can be planted
          type: number
          format: float
          example: 2.32
        carbonSequestered:
          description: Calculated Carbon Sequestered Score after planting trees from the donation being made
          type: number
          format: double
          example: 1234.45
        conversionRate:
          description: Conversion Rate at which the user's currency equivalent in USD
          type: number
          format: float
          example: 2.3456
        conversionRateDate:
          description: The date at which conversion rate was last updated
          type: string
          format: date
          example: '2021-03-15'
    PlantingProject:
      type: object
      properties:
        id:
          description: The id of the planting project, as stored in priceless planet records.
          type: integer
          format: int64
          readOnly: true
          example: 1
        countryName:
          $ref: '#/components/schemas/CountryName'
        target:
          $ref: '#/components/schemas/TreePlantingTarget'
        treesPlanted:
          $ref: '#/components/schemas/TreePlantingTotal'
        areaCovered:
          $ref: '#/components/schemas/AreaCovered'
        carbonSequestered:
          $ref: '#/components/schemas/CarbonSequestered'
        name:
          $ref: '#/components/schemas/ProjectName'
        description:
          $ref: '#/components/schemas/ProjectDescription'
        images:
          description: Image of planting project if exists any in priceless planet records
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Image'
    PlantingProjects:
      type: object
      properties:
        count:
          $ref: '#/components/schemas/PaginationCount'
        limit:
          $ref: '#/components/schemas/PaginationLimit'
        offset:
          $ref: '#/components/schemas/PaginationOffset'
        total:
          $ref: '#/components/schemas/PaginationTotal'
        plantingProjects:
          description: List of planting projects
          type: array
          items:
            $ref: '#/components/schemas/PlantingProject'
    PaginationCount:
      type: integer
      format: int32
      description: The number of items that are in this offset batch
      example: 10
    PaginationLimit:
      type: integer
      format: int32
      description: The number of items the list has been limited to
      example: 10
    PaginationOffset:
      type: integer
      format: int32
      description: The number of items the start of the list has been offset from
      example: 0
    PaginationTotal:
      type: integer
      format: int64
      description: The total number of items that are in the entire collection
      example: 15
    TreePlantingTarget:
      type: integer
      format: int64
      example: 2000000
    TreePlantingTotal:
      type: integer
      format: int64
      example: 1680000
    AreaCovered:
      type: number
      format: double
      example: 94
    CarbonSequestered:
      type: integer
      format: int64
      example: 50
    ProjectName:
      type: string
      example: Amazon Rainforest
      pattern: ^[a-zA-Z0-9\s'’\-\.\$(),%—\/]+$
      maxLength: 50
    ProjectDescription:
      type: string
      maxLength: 1000
      pattern: ^[a-zA-Z0-9\s'’\-\.\$£€(),]+$
      example: >-
        The Atlantic Forest, also known as Mata Atlantica, once covered 130 million hectares across Brazil.
        Now, this tropical rainforest ecosystem is home to more than half of the country’s population.
    CountryName:
      type: string
      description: ISO 3166 country short name
      pattern: ^[a-zA-Z\s\\(\\),\\.]+$
      minLength: 3
      maxLength: 50
      example: Brazil
    Image:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: Specifies the path to the image
          minLength: 10
          maxLength: 100
          example: https:image
    ErrorWrapper:
      type: object
      required:
        - Errors
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
    Errors:
      type: object
      required:
        - Error
      properties:
        Error:
          $ref: '#/components/schemas/ErrorList'
    ErrorList:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/Error'
    Error:
      title: Error
      type: object
      description: Error object which contains details about error.
      required:
        - Source
        - ReasonCode
        - Description
        - Recoverable
      properties:
        Source:
          type: string
          description: The application name that generated this error. Every error message that is generated and returned by the gateway will have this field equal to Gateway.
          minLength: 1
          maxLength: 100
          example: 'Priceless Planet Consumer Metrics'
        ReasonCode:
          type: string
          description: A unique constant identifying the error case encountered during request processing.
          minLength: 1
          maxLength: 100
          example: 'INVALID_REQUEST_PARAMETER'
        Description:
          type: string
          description: Short description of the ReasonCode field.
          minLength: 10
          maxLength: 1000
          example: 'The currency entered is invalid. Try again with a valid currency.'
        Recoverable:
          type: boolean
          description: Indicates whether this error will always be returned for this request, or retrying could change the outcome.
          example: false
        Details:
          type: string
          description: (Optional) Where appropriate, indicates detailed information about data received and calculated during request processing, to help the user with diagnosing errors.
          minLength: 0
          maxLength: 5000
          example: ''
  responses:
    ImpactMetrics:
      description: Impact Metrics
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImpactMetric'
          examples:
            ImpactMetricsExample:
              $ref: '#/components/examples/ImpactMetricsExample'
    ImpactMetricsBadRequestError:
      description: Impact Metrics Bad Request Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            ImpactMetricsBadRequestError:
              $ref: '#/components/examples/ImpactMetricsBadRequestErrorExample'
    ImpactMetricsCurrencyNotFoundError:
      description: Impact Metrics Not Found Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            ImpactMetricsBadDonationAmountError:
              $ref: '#/components/examples/ImpactMetricsCurrencyNotFoundErrorExample'
    PlantingProjects:
      description: Planting Projects were successfully retrieved.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PlantingProjects'
    PlantingProjectsBadRequestError:
      description: Planting Projects Bad Request Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            PlantingProjectsBadLimitRequestError:
              $ref: '#/components/examples/PlantingProjectsBadRequestErrorExample'
    PlantingProject:
      description: Planting Project was successfully retrieved.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PlantingProject'
    PlantingProjectBadRequestError:
      description: Planting Project Bad Request Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            PlantingProjectsBadLimitRequestError:
              $ref: '#/components/examples/PlantingProjectBadRequestErrorExample'
    PlantingProjectNotFoundError:
      description: Planting Project Not Found Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            PlantingProjectsBadLimitRequestError:
              $ref: '#/components/examples/PlantingProjectNotFoundErrorExample'
  examples:
    ImpactMetricsExample:
      value:
        trees: 239.45
        carbonSequestered: 123456.34
        conversionRate: 0.278
        conversionRateDate: 2021-03-15
    ImpactMetricsBadRequestErrorExample:
      value:
        Errors:
          Error:
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'One of the request parameters is invalid, try again with correct request.'
              Recoverable: false
              Details: 'Donation Amount should be a valid positive number'
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'One of the request parameters is invalid, try again with correct request.'
              Recoverable: false
              Details: 'Currency Should be a valid string following ISO-4217 example USD.'
    ImpactMetricsCurrencyNotFoundErrorExample:
      value:
        Errors:
          Error:
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'CURRENCY_NOT_FOUND'
              Description: 'Requested currency is either not valid or cannot be found.'
              Recoverable: false
              Details: ''
    PlantingProjectsBadRequestErrorExample:
      value:
        Errors:
          Error:
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'One of the request parameters is invalid, try again with correct request.'
              Recoverable: false
              Details: 'Limit value should be positive numbers'
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'One of the request parameters is invalid, try again with correct request.'
              Recoverable: false
              Details: 'Offset value should be positive numbers'
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'One of the request parameters is invalid, try again with correct request.'
              Recoverable: false
              Details: 'Sort value should be a valid string, see schema description for more details'
    PlantingProjectBadRequestErrorExample:
      value:
        Errors:
          Error:
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'INVALID_REQUEST_PARAMETER'
              Description: 'The given id is invalid, try again with correct request.'
              Recoverable: false
              Details: 'id value should be a positive number'
    PlantingProjectNotFoundErrorExample:
      value:
        Errors:
          Error:
            - Source: 'Priceless Planet Consumer Metrics'
              ReasonCode: 'PLANTING_PROJECT_NOT_FOUND'
              Description: 'Requested planting project with given id cannot be found.'
              Recoverable: false
              Details: 'id value should be a positive number'